version: 2.1
orbs:
  codecov: codecov/codecov@1.0.5
jobs:
  build:
    machine:
      image: ubuntu-1604:201903-01

    working_directory: ~/repo

    steps:

      - checkout # checkout src code to working dir

      - run:
         name: install global deps
         command: sudo apt-get update && sudo apt-get install libopenmpi-dev openmpi-common openmpi-bin vtk6 libvtk6-dev python3-pip

      - run:
          name: clone PyGranParams
          command: | 
            pip3 install --upgrade pip --user
            git clone https://github.com/Andrew-AbiMansour/PyGranParams
            cd PyGranParams
            pip3 install . --user
            cd ..

      - run:
          name: install PyGranSim deps
          command: |
            pip3 install codecov --user
            pip3 install -e .[extra] --user

      - run:
          name: compile LIGGGHTS
          command: |
            python3 setup.py build_liggghts

      - run:
          name: install PyGranSim
          command: |
            pip3 install . --user

      - run:
          name: run tests
          command: |
            $HOME/.local/bin/pytest --cov=PyGranSim tests

      - run:
          name: run code coverage
          command: |
            $HOME/.local/bin/codecov

      - codecov/upload:
          file: coverage.xml
          flags: frontend

      - store_test_results:
          path: tests
